# Use postgres/example user/password credentials

services:
  db:
    image: postgres:17-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volume:
      - ./data/:/var/lib/postgresql/
    env_file:
      - .env.docker
